name: Force Reset

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with default token
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Reset to commit
        run: |
          git reset --hard 111750258389eec6d57c0e545252d5c4ee711d12
          git push origin HEAD:refs/heads/main --force
