# .github/workflows/reset.yml
name: Force Reset to Commit

on:
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # required for push

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0

      - name: Force reset to specific commit
        run: |
          git reset --hard 111750258389eec6d57c0e545252d5c4ee711d12
          git push origin HEAD:refs/heads/main --force
