# .github/workflows/reset-branch.yml
name: Reset Branch

on:
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Reset branch to specific commit
        run: |
          git reset --hard <good_commit_sha>
          git push origin HEAD:refs/heads/main --force
